export default {
    TAB_ROUTES: "TabRoutes",
    SIGN_UP: "SignUp",
    SIGN_IN: "SignIn",
    OTP_VERIFICATION: "OtpVerification",
    BOOKING: "Booking",
    CART: "Cart",
    GALLERY: "Gallery",
    HOME: "Home",
    PROFILE: "Profile",
    STORE: "Store",
    SUB_CATEGORY: "Subcategory",
    SERVICE_INFO: "ServiceInfo",
    CHECKOUT: "Checkout",
}